# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1a8ab1f1496f173a1931592f5f27df4c25118ec7cf398df90993f6509c0e8fedcb37deab38ffa9298898cce940342e945f1855659c3930627fe011cec2ab0d6a

test:
  secret_key_base: 94e73b3cbe59b9e7405000471e7721b7d4e2dcf3c249bb252899551aaccfacaa8276527b7eb738ff098b7a2939ba91a195a847d7e0bc91a5fc5d1b93e23c657b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
